name: bookmark_blade
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bookmark_models:
    git:
      ref: master
      url: git@github.com:VHCBlade/bookmark_models.git

  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2

  event_essay: ^0.1.1
  event_bloc: ^4.2.0
  event_db: ^0.1.7
  # event_db:
  #   path: ../event_db
  event_hive: ^0.1.3
  # event_hive:
  #   path: ../event_hive
  event_navigation: ^0.6.4+1
  # event_navigation:
  #   path: ../event-navigation
  # event_ads: ^0.1.0
  # event_ads:
  #   path: ../event_ads
  event_modals: ^0.1.2
  search_me_up: ^0.1.1

  vhcblade_theme: ^0.2.3
  # vhcblade_theme:
  #   path: ../vhcblade_theme

  fl_chart: ^0.61.0
  flutter_markdown: ^0.6.13
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^13.0.0
  google_sign_in: ^6.0.2
  # google_mobile_ads: ^2.3.0
  
  http: ^0.13.0
  intl: ^0.18.0
  math_parser: ^1.5.0
  provider: ^6.0.0
  timezone: ^0.9.1
  tuple: ^2.0.0
  fluttertoast: ^8.2.1

  url_launcher: ^6.1.10
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  event_bloc_tester: ^0.1.1

flutter:

  uses-material-design: true
